---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- KubeVirt 虚拟化集群:
    - KubeVirt-Shoryu:
        icon: si-kubevirt
        description: "CPU: R7-5825U / MEM: 64G / DISK: 1T"
        href: https://grafana.writefor.fun/d/rYdddlPWk/node-exporter-full?orgId=1&var-node=192.168.5.181:9100
        siteMonitor: https://grafana.writefor.fun/d/rYdddlPWk/node-exporter-full?orgId=1&var-node=192.168.5.181:9100
    - KubeVirt-Shushou:
        icon: si-kubevirt
        description: "CPU: R9-5900HX / MEM: 64G / DISK: 1T"
        href: https://grafana.writefor.fun/d/rYdddlPWk/node-exporter-full?orgId=1&var-node=192.168.5.182:9100
        siteMonitor: https://grafana.writefor.fun/d/rYdddlPWk/node-exporter-full?orgId=1&var-node=192.168.5.182:9100
    - KubeVirt-Youko:
        icon: si-kubevirt
        description: "CPU: R5-5625U / MEM: 32G / DISK: 512G+4T*2"
        href: https://grafana.writefor.fun/d/rYdddlPWk/node-exporter-full?orgId=1&var-node=192.168.5.183:9100
        siteMonitor: https://grafana.writefor.fun/d/rYdddlPWk/node-exporter-full?orgId=1&var-node=192.168.5.183:9100
    - LongHorn-Storage:
        icon: si-longhorn
        href: http://longhorn.writefor.fun/
    - Victoria-Metrics:
        icon: si-victoriametrics
        href: http://vm.writefor.fun/
    - KubeVirt-Grafana:
        icon: si-grafana
        href: http://k8s-grafana.writefor.fun/

- Homelab Monitoring:
    - Grafana:
        icon: si-grafana
        href: https://grafana.writefor.fun
        description: Data visualised on dashboards
        siteMonitor: https://grafana.writefor.fun
    - Prometheus Dashboard:
        icon: si-prometheus
        href: https://prometheus.writefor.fun
        description: Monitoring - Prometheus
        siteMonitor: https://prometheus.writefor.fun
    - Uptime Kuma:
        icon: si-uptimekuma
        href: https://uptime-kuma.writefor.fun
        description: Uptime Checking
        siteMonitor: https://uptime-kuma.writefor.fun

- Homelab Applications:
    - SFTPGO:
      icon: sftpgo.png
      href: "https://sftpgo.writefor.fun/web/admin/folders"
      description: WebDAV & SFTP server
      siteMonitor: https://sftpgo.writefor.fun/
# - Kubernetes Monitoring:
#     # TODO: Update this
#     - Emby:
#       icon: emby.png
#       href: "http://emby.home/"
#       description: Media server
#       namespace: media # The kubernetes namespace the app resides in
#       app: emby # The name of the deployed app
#
#     - Element Chat:
#         icon: matrix-light.png
#         href: https://chat.example.com
#         description: Matrix Synapse Powered Chat
#         app: matrix-element
#         namespace: comms
#         pod-selector: >-
#           app.kubernetes.io/instance in (
#               matrix-element,
#               matrix-media-repo,
#               matrix-media-repo-postgresql,
#               matrix-synapse
#           )
