---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Ryan Yin's Homelab
base: https://home.writefor.fun/
favicon: https://thiscute.world/favicon.ico

# https://developer.mozilla.org/en-US/docs/Web/Manifest/start_url
# Used by some browsers to determine the start page of the web application
startUrl: https://home.writefor.fun/

language: zh

# Define shared API provider options and secrets here,
# You can then pass provider instead of apiKey in your widget configuration.
providers:
  # read api keys from environment variables
  openweathermap: { { HOMEPAGE_VAR_WEATHERAPI_APIKEY } }
  weatherapi: { { HOMEPAGE_VAR_WEATHERAPI_APIKEY } }

background:
  image: https://file.writefor.fun/wallpapers/rolling-girls.png
  blur: sm # 模糊 - sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 90 # 色彩饱和度 - 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 90 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 25 # 透明度 - 0-100

theme: dark # or light

# Supported colors are:
# slate, gray, zinc, neutral, stone, amber,
# yellow, lime, green, emerald, teal, cyan,
# sky, blue, indigo, violet, purple, fuchsia, pink, rose, red, white
color: slate

# make all cards in a row the same height.
useEqualHeights: true

# Groups and its layout
# Groups Name should match the name defined in your services.yaml or widgets.yaml
layout:
  Homelab Monitoring:
    icon: mdi-monitor-dashboard
    initiallyCollapsed: false # collapsed by default
    tab: Main
    style: row
    columns: 3

  Homelab Applications:
    icon: si-homepage
    tab: Main

  KubeVirt 虚拟化集群:
    icon: si-kubernetes
    tab: KubeVirt

# https://gethomepage.dev/latest/configs/services/#icons
# iconStyle: theme # optional, defaults to gradient

# Typing in homepage to quick search
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true

# Show docker stats
showStats: true

hideErrors: false
